### ISSUE TITLE
Java 10 appears to interpret classpath as unrecognized protocol

### ISSUE THREAD

**Issue by ajnelson-nist** [usnistgov/swid-tools#1]
I have the SWID Autotools repository using Travis now.  I tried a build (build record [here](https://travis-ci.com/usnistgov/private_swid_autotools/jobs/164171333), let me know if you need access permissions) that used macOS and Ubuntu to run swidval against a small tag, and the macOS side failed, seemingly because a classpath is accidentally being interpreted as a protocol.

Java versions (per `Build system information` from the Travis logs):
* Ubuntu: `Java version: 1.8.0_151, vendor: Oracle Corporation`
* macOS: `Java version: 10.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home`

Relevant build log snippets:
* Ubuntu:
```
[... stuff that worked ...]
java -jar swidval-0.5.0.jar -usecase corpus /home/travis/build/usnistgov/private_swid_autotools/tests/sample_nop_corpus_tag/base.swidtag
2018-12-10 22:07:30 INFO  Validating tag: /home/travis/build/usnistgov/private_swid_autotools/tests/sample_nop_corpus_tag/base.swidtag
2018-12-10 22:07:30 INFO    tag type: corpus
2018-12-10 22:07:30 INFO    authoritative tag: true
2018-12-10 22:07:31 INFO  Loading requirements from: classpath:requirements.xml
[... and then it goes on working ...]
```
* macOS:
```
[... stuff that worked ...]
java -jar swidval-0.5.0.jar -usecase corpus /Users/travis/build/usnistgov/private_swid_autotools/tests/sample_nop_corpus_tag/base.swidtag
2018-12-10 22:10:13 INFO  Validating tag: /Users/travis/build/usnistgov/private_swid_autotools/tests/sample_nop_corpus_tag/base.swidtag
2018-12-10 22:10:13 INFO    tag type: corpus
2018-12-10 22:10:13 INFO    authoritative tag: true
Exception in thread "main" java.lang.RuntimeException: java.net.MalformedURLException: unknown protocol: classpath
	at gov.nist.decima.swid.SWIDRequirementsManager.<init>(SWIDRequirementsManager.java:64)
	at gov.nist.decima.swid.SWIDRequirementsManager.getInstance(SWIDRequirementsManager.java:50)
	at gov.nist.decima.swid.SWIDAssessmentReactor.<init>(SWIDAssessmentReactor.java:55)
	at gov.nist.decima.swid.Application.run(Application.java:178)
	at gov.nist.decima.swid.Application.main(Application.java:82)
Caused by: java.net.MalformedURLException: unknown protocol: classpath
	at java.base/java.net.URL.<init>(URL.java:634)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/java.net.URL.<init>(URL.java:470)
	at gov.nist.decima.swid.SWIDRequirementsManager.<init>(SWIDRequirementsManager.java:60)
	... 4 more
make[3]: *** [validation-result.xml] Error 1
```

Steps to reproduce:
* Install Oracle Java 10.  (I'm guessing OS won't matter, but Java version will.)
* Clone [this repository](https://github.com/usnistgov/swidval/issues/new).  (This issue confirmed on commit `ddc261c`.)
* Run `make check-swidval`.

**Comment by ajnelson-nist** [comment]
As a reminder of the relevance of this issue, which I ran into again recently: The Ubuntu package `default-jre` installs Java 11 by default.

**Comment by ajnelson-nist** [comment]
Thanks!
